const onderzoekendummy = [
    {
        id: 1,
        titel: 'Toegankelijkheid van Webformulieren',
        beschrijving: 'Onderzoek naar de toegankelijkheid van webformulieren voor gebruikers met verschillende beperkingen.',
        uitvoerder: 'Stichting Accessibility',
        datum: '15 januari 2024',
        locatie: 'Online',
        beloning: '€20',
        type: 'Interview',
        status: 'Open',
    },
    {
        id: 2,
        titel: 'Navigatie op Websites voor Slechtzienden',
        beschrijving: 'Evaluatie van de navigatie-ervaring op verschillende websites voor slechtziende gebruikers.',
        uitvoerder: 'ABC Company',
        datum: '20 februari 2024',
        locatie: 'Online',
        beloning: '€15',
        type: 'Online onderzoek',
        status: 'Open',
    },
    {
        id: 3,
        titel: 'Navigatie ',
        beschrijving: 'Evaluatie van de navigatie-ervaring op verschillende websites voor slechtziende gebruikers.',
        uitvoerder: 'ABC Company',
        datum: '20 februari 2024',
        locatie: 'Online',
        beloning: '€15',
        type: 'Online onderzoek',
        status: 'Open',
    },
    {
        id: 4,
        titel: 'Navigatie op Websites voor kleurenblinden',
        beschrijving: 'Evaluatie van de navigatie-ervaring op verschillende websites voor slechtziende gebruikers.',
        uitvoerder: 'ABC Company',
        datum: '20 februari 2024',
        locatie: 'Online',
        beloning: '€15',
        type: 'Engelstalig onderzoek',
        status: 'Open',
    },
];

export default onderzoekendummy;
