const userDummyData = [
    {
        id: 1,
        firstName: 'John',
        lastName: 'Doe',
        email: 'john.doe@example.com',
        phoneNumber: '0612345679',
        password: 'Test@123',
        gender: 'man',
        birthDate: '1995-01-01',
    },
    {
        id: 2,
        firstName: 'Jane',
        lastName: 'Doe',
        email: 'jane.doe@example.com',
        phoneNumber: '0612345678',
        password: 'Test@123',
        gender: 'vrouw',
        birthDate: '1991-02-02',
    },
    {
        id: 1,
        firstName: 'John',
        lastName: 'Doe',
        email: 'john.doe@example.com',
        phoneNumber: '0612345679',
        password: 'Test@123',
        gender: 'man',
        birthDate: '1990-01-01',
    },
    {
        id: 2,
        firstName: 'Jane',
        lastName: 'Doe',
        email: 'jane.doe@example.com',
        phoneNumber: '0612345678',
        password: 'Test@123',
        gender: 'vrouw',
        birthDate: '1991-02-02',
    },
    {
        id: 1,
        firstName: 'John',
        lastName: 'Doe',
        email: 'john.doe@example.com',
        phoneNumber: '0612345679',
        password: 'Test@123',
        gender: 'man',
        birthDate: '1990-01-01',
    },
    {
        id: 2,
        firstName: 'Jane',
        lastName: 'Doe',
        email: 'jane.doe@example.com',
        phoneNumber: '0612345678',
        password: 'Test@123',
        gender: 'vrouw',
        birthDate: '1991-02-02',
    },
    {
        id: 1,
        firstName: 'John',
        lastName: 'Doe',
        email: 'john.doe@example.com',
        phoneNumber: '0612345679',
        password: 'Test@123',
        gender: 'man',
        birthDate: '1990-01-01',
    },
    {
        id: 2,
        firstName: 'Jane',
        lastName: 'Doe',
        email: 'jane.doe@example.com',
        phoneNumber: '0612345678',
        password: 'Test@123',
        gender: 'vrouw',
        birthDate: '1991-02-02',
    },
    {
        id: 1,
        firstName: 'John',
        lastName: 'Doe',
        email: 'john.doe@example.com',
        phoneNumber: '0612345679',
        password: 'Test@123',
        gender: 'man',
        birthDate: '1990-01-01',
    },
    {
        id: 2,
        firstName: 'Jane',
        lastName: 'Doe',
        email: 'jane.doe@example.com',
        phoneNumber: '0612345678',
        password: 'Test@123',
        gender: 'vrouw',
        birthDate: '1991-02-02',
    },
    {
        id: 1,
        firstName: 'John',
        lastName: 'Doe',
        email: 'john.doe@example.com',
        phoneNumber: '0612345679',
        password: 'Test@123',
        gender: 'man',
        birthDate: '1990-01-01',
    },
    {
        id: 2,
        firstName: 'Jane',
        lastName: 'Doe',
        email: 'jane.doe@example.com',
        phoneNumber: '0612345678',
        password: 'Test@123',
        gender: 'vrouw',
        birthDate: '1991-02-02',
    },
    {
        id: 1,
        firstName: 'John',
        lastName: 'Doe',
        email: 'john.doe@example.com',
        phoneNumber: '0612345679',
        password: 'Test@123',
        gender: 'man',
        birthDate: '1990-01-01',
    },
    {
        id: 2,
        firstName: 'Jane',
        lastName: 'Doe',
        email: 'jane.doe@example.com',
        phoneNumber: '0612345678',
        password: 'Test@123',
        gender: 'wil ik liever niet zeggen',
        birthDate: '1991-02-02',
    },
];

export default userDummyData;
